#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

function pre_commit_sirc_vm {
    pushd sirc-vm
    cargo fmt --all
    cargo build --release
    cargo clippy --all-targets --all-features -- -D warnings
    cargo nextest run
    popd
}

function pre_commit_sirc_tiledit {
    pushd sirc-tiledit/build
    meson compile -v
    meson test --print-errorlogs
    ninja clang-tidy
    ninja clang-format-check
    popd
}

CHANGED_FILES=$(git diff --cached --name-only)

echo "$CHANGED_FILES"

if echo "$CHANGED_FILES" | grep --quiet "^sirc-vm"
then
    pre_commit_sirc_vm
fi

if echo "$CHANGED_FILES" | grep --quiet "^sirc-tiledit"
then
    pre_commit_sirc_tiledit
fi
