#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

pushd sirc-vm
cargo fmt --all
cargo build --release
cargo clippy --all-targets --all-features -- -D warnings
cargo test --verbose
popd
