[package]
name = "peripheral_cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
peripheral_mem = { path = "../peripheral-mem" }
enum_dispatch = "0.3.12"
num-traits = "0.2"
num-derive = "0.4"
num = "0.4"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
strum = { version = "0.25", features = ["derive"] }
