[package]
name = "sbrc-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.8"
nannou = "0.18.1"
nannou_audio = "0.18.0"
