[package]
name = "sbrc_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
peripheral_clock = { path = "../peripheral-clock" }
peripheral_cpu = { path = "../peripheral-cpu" }
peripheral_mem = { path = "../peripheral-mem" }
peripheral_terminal = { path = "../peripheral-terminal" }
device_ram = { path = "../device-ram" }
