name: Upload Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--deny warnings"

jobs:
  sirc-tiledit:
    uses: ./.github/workflows/sirc-tiledit.yml
  upload-to-codecov:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs: [sirc-tiledit]
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: List artifacts
        run: find .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: >
            codecov-basic-video/codecov-*.json,
            codecov-boring/codecov-*.json,
            codecov-byte-sieve/codecov-*.json,
            codecov-faults/codecov-*.json,
            codecov-hardware-exception/codecov-*.json,
            codecov-main/codecov-*.json,
            codecov-software-exception/codecov-*.json,
            codecov-store-load/codecov-*.json,
            coverage.xml
          fail_ci_if_error: true
